#All path MUST start by /api/

index:
  path: /api/
  controller: App\Controller\DefaultController::index
  methods:  [GET]

index_detailed_url:
  path: /api/index
  controller: App\Controller\DefaultController::index
  methods:  [GET]




user_getter:
  path: /api/user/{id}
  controller: App\Controller\UserController::getUser
  defaults:
    id: null
  methods:  [GET]

user_register:
  path: /api/user
  controller: App\Controller\UserController::register
  methods:  [POST]



file_getter:
  path: /api/file/{id}
  controller: App\Controller\FileController::getFile
  methods:  [GET]

save_file:
  path: /api/file
  controller: App\Controller\FileController::saveFile
  methods:  [POST]





app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
