#All path MUST start by /api/

index:
  path: /api/
  controller: App\Controller\DefaultController::index

index_detailed_url:
  path: /api/index
  controller: App\Controller\DefaultController::index

user_index:
  path: /api/user
  controller: App\Controller\UserController::index
  methods:  [GET]

user_register:
  path: /api/user/register
  controller: App\Controller\UserController::register
  methods:  [POST]


file_index:
  path: /api/file
  controller: App\Controller\FileController::index
  methods:  [GET]

save_file:
  path: /api/file/upload
  controller: App\Controller\FileController::saveFile
  methods:  [POST]

get_file_by_id:
  path: /api/file/get/{id}
  controller: App\Controller\FileController::getFile
  methods:  [GET]
